In [27]:
import numpy as np
import numpy.linalg as alg

# Define the matrix H
H = np.array([[0.1, 0.15, 0.40],
              [0.3, 0.45, 1.20]])

print(alg.norm(H[1, :]))




1.3162446581088183


In [28]:
F = np.round(H.T/alg.norm(H, "fro"), 4)
x = np.array([0.4, 0.2, 0.1])
n = np.array([0.01, 0.03, 0.01])

In [30]:
F


array([[0.0721, 0.2162],
       [0.1081, 0.3243],
       [0.2883, 0.8649]])

In [12]:

y = F @ H @x + n

In [13]:
y

array([0.0892825 , 0.14892375, 0.32712999])

In [31]:
H @x

array([0.11, 0.33])

In [35]:
F @ H @x+n


array([0.089277, 0.14891 , 0.32713 ])

In [36]:
F[:, 0] / F[:, 1]

array([0.33348751, 0.33333333, 0.33333333])

In [22]:
H @ x

array([0.11, 0.33])

In [23]:
y_ = np.round(y, 2)

In [24]:
y_

array([0.09, 0.15, 0.33])

In [25]:
alg.MSE(x, y_)

AttributeError: module 'numpy.linalg' has no attribute 'MSE'

In [26]:
np.mean((x - y_)**2)

0.05050000000000001